<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CafeMenuManager.BLL\CafeMenuManager.BLL.csproj" />
    <ProjectReference Include="..\CafeMenuManager.Model\CafeMenuManager.Model.csproj" />
  </ItemGroup>

</Project>
